#!/bin/sh

uid=$(echo ${CACHE_TAG} | awk 'BEGIN {FS="_"} {print $2}')
gid=$(echo ${CACHE_TAG} | awk 'BEGIN {FS="_"} {print $3}')

echo "building with UID=${uid} and GID=${gid} based on CACHE_TAG=${CACHE_TAG}"
docker build --build-arg UID=${uid} --build-arg GID=${gid} -f ${DOCKERFILE_PATH} -t ${IMAGE_NAME} .
